wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.10
    start_time: 1685801937.368848
    t:
      1:
      - 1
      - 2
      - 3
      - 30
      - 55
      2:
      - 1
      - 2
      - 3
      - 30
      - 55
      3:
      - 23
      4: 3.10.10
      5: 0.14.0
      8:
      - 3
      - 5
