wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.3
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685614227.239929
    t:
      1:
      - 2
      - 3
      - 30
      - 55
      2:
      - 2
      - 3
      - 30
      - 55
      3:
      - 23
      4: 3.10.10
      5: 0.15.3
      8:
      - 3
      - 5
